// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"database/sql"
	"time"
)

type Gamemode40l struct {
	ID             int64
	PlayedAt       time.Time
	Time           float64
	FinessePercent float64
	FinesseFaults  int64
	TotalPieces    int64
	RawData        sql.NullString
}
