// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package store

import (
	"database/sql"
	"time"
)

type Gamemode40l struct {
	ID              int64
	PlayedAt        time.Time
	TimeMs          int64
	FinessePercent  float64
	TotalPieces     int64
	PiecesPerSecond float64
	RawData         sql.NullString
}
