// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const getLatestGamemode40L = `-- name: GetLatestGamemode40L :one
SELECT played_at
FROM gamemode_40l
ORDER BY played_at DESC
LIMIT 1
`

func (q *Queries) GetLatestGamemode40L(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getLatestGamemode40L)
	var played_at time.Time
	err := row.Scan(&played_at)
	return played_at, err
}

const insertGamemode40L = `-- name: InsertGamemode40L :one
INSERT INTO gamemode_40l (
  played_at,
  time_ms,
  finesse_percent,
  total_pieces,
  pieces_per_second,
  raw_data
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, played_at, time_ms, finesse_percent, total_pieces, pieces_per_second, raw_data
`

type InsertGamemode40LParams struct {
	PlayedAt        time.Time
	TimeMs          int64
	FinessePercent  float64
	TotalPieces     int64
	PiecesPerSecond float64
	RawData         sql.NullString
}

func (q *Queries) InsertGamemode40L(ctx context.Context, arg InsertGamemode40LParams) (Gamemode40l, error) {
	row := q.db.QueryRowContext(ctx, insertGamemode40L,
		arg.PlayedAt,
		arg.TimeMs,
		arg.FinessePercent,
		arg.TotalPieces,
		arg.PiecesPerSecond,
		arg.RawData,
	)
	var i Gamemode40l
	err := row.Scan(
		&i.ID,
		&i.PlayedAt,
		&i.TimeMs,
		&i.FinessePercent,
		&i.TotalPieces,
		&i.PiecesPerSecond,
		&i.RawData,
	)
	return i, err
}
