// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0
// source: queries.sql

package store

import (
	"context"
	"database/sql"
	"time"
)

const insertGamemode40L = `-- name: InsertGamemode40L :one
INSERT INTO gamemode_40l (
  played_at,
  time_ms,
  finesse_percent,
  finesse_faults,
  total_pieces,
  raw_data
) VALUES (
  ?, ?, ?, ?, ?, ?
)
RETURNING id, played_at, time_ms, finesse_percent, finesse_faults, total_pieces, raw_data
`

type InsertGamemode40LParams struct {
	PlayedAt       time.Time
	TimeMs         int64
	FinessePercent float64
	FinesseFaults  int64
	TotalPieces    int64
	RawData        sql.NullString
}

func (q *Queries) InsertGamemode40L(ctx context.Context, arg InsertGamemode40LParams) (Gamemode40l, error) {
	row := q.db.QueryRowContext(ctx, insertGamemode40L,
		arg.PlayedAt,
		arg.TimeMs,
		arg.FinessePercent,
		arg.FinesseFaults,
		arg.TotalPieces,
		arg.RawData,
	)
	var i Gamemode40l
	err := row.Scan(
		&i.ID,
		&i.PlayedAt,
		&i.TimeMs,
		&i.FinessePercent,
		&i.FinesseFaults,
		&i.TotalPieces,
		&i.RawData,
	)
	return i, err
}
